# Development environment overrides for Podman Compose
# Use with: podman-compose -f podman-compose.yml -f podman-compose.dev.yml up

version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: sanguine_scribe_dev
    ports:
      - "5432:5432"
    volumes:
      - ../configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro,Z
    
  qdrant:
    environment:
      QDRANT__SERVICE__ENABLE_TLS: "false"  # Disable TLS for development
    ports:
      - "6333:6333"
      - "6334:6334"
    # Override volumes to skip TLS certs in development
    volumes:
      - qdrant_data:/qdrant/storage