# Container development environment overrides for Podman Compose
# For running everything containerized locally (backend + postgres + qdrant)  
# Use with: podman-compose -f podman-compose.yml -f podman-compose.container.yml up

version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: sanguine_scribe_dev
    ports:
      - "5432:5432"
    volumes:
      - ../configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro,Z
      - ${POSTGRES_CERT_PATH:-../../../.certs-postgres}:/var/lib/postgresql/certs:ro,z
      
  qdrant:
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${QDRANT_CERT_PATH:-../../../.certs-qdrant}:/qdrant_certs:ro,z
      
  # Backend service for containerized development
  backend:
    image: localhost/scribe-backend:latest
    container_name: scribe_backend_dev
    env_file:
      - ../../../.env
    environment:
      # Override container-specific settings
      - DATABASE_URL=postgresql://devuser:devpassword@postgres:5432/sanguine_scribe_dev
      - QDRANT_URL=https://qdrant:6334
      - ENVIRONMENT=container
      - RUST_LOG=debug
      - PORT=8080
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - qdrant
    # No volumes needed - certificates are embedded in the container image
    restart: unless-stopped