-- NOTE: In SQLite, FLOAT and DOUBLE both map to REAL storage class
-- No database changes needed - this migration documents the schema.rs change
--
-- The following columns will be represented as Double (not Float) in schema.rs
-- to match DbDecimal's Expression::SqlType = Double:
--
-- chat_messages table:
--   - actual_cost: REAL (schema.rs: Double)
--   - modified_cost: REAL (schema.rs: Double)
--   - actual_charge: REAL (schema.rs: Double)
--
-- chat_sessions table:
--   - total_actual_cost: REAL (schema.rs: Double)
--   - total_modified_cost: REAL (schema.rs: Double)
--   - total_actual_charge: REAL (schema.rs: Double)
--
-- After running `diesel print-schema`, these columns will need to be changed
-- from Float to Double in schema.rs to match DbDecimal trait implementation.

-- No-op migration (database already correct)
SELECT 1;
