-- Add missing columns to the characters table to match models/characters.rs

ALTER TABLE characters
    ADD COLUMN persona TEXT NULL,
    ADD COLUMN world_scenario TEXT NULL,
    ADD COLUMN avatar TEXT NULL,
    ADD COLUMN chat TEXT NULL,
    ADD COLUMN greeting TEXT NULL,
    ADD COLUMN definition TEXT NULL,
    ADD COLUMN default_voice TEXT NULL,
    ADD COLUMN extensions JSONB NULL,
    ADD COLUMN data_id INTEGER NULL,
    -- alternate_greetings is already present in initial migration
    ADD COLUMN category VARCHAR(255) NULL,
    ADD COLUMN definition_visibility VARCHAR(50) NULL,
    ADD COLUMN depth INTEGER NULL,
    ADD COLUMN example_dialogue TEXT NULL,
    ADD COLUMN favorite BOOLEAN NULL,
    ADD COLUMN first_message_visibility VARCHAR(50) NULL,
    ADD COLUMN height NUMERIC NULL,
    ADD COLUMN last_activity TIMESTAMPTZ NULL,
    ADD COLUMN migrated_from VARCHAR(255) NULL,
    ADD COLUMN model_prompt TEXT NULL,
    ADD COLUMN model_prompt_visibility VARCHAR(50) NULL,
    ADD COLUMN model_temperature NUMERIC NULL,
    ADD COLUMN num_interactions BIGINT NULL,
    ADD COLUMN permanence NUMERIC NULL,
    ADD COLUMN persona_visibility VARCHAR(50) NULL,
    ADD COLUMN revision INTEGER NULL,
    ADD COLUMN sharing_visibility VARCHAR(50) NULL,
    ADD COLUMN status VARCHAR(50) NULL,
    ADD COLUMN system_prompt_visibility VARCHAR(50) NULL,
    ADD COLUMN system_tags TEXT[] NULL,
    ADD COLUMN token_budget INTEGER NULL,
    ADD COLUMN usage_hints JSONB NULL,
    ADD COLUMN user_persona TEXT NULL,
    ADD COLUMN user_persona_visibility VARCHAR(50) NULL,
    ADD COLUMN visibility VARCHAR(50) NULL,
    ADD COLUMN weight NUMERIC NULL,
    ADD COLUMN world_scenario_visibility VARCHAR(50) NULL;
    -- creator_notes_multilingual is already present in initial migration
