// Desktop user management for local-only authentication
//
// This module handles automatic user creation and management for desktop mode,
// ensuring a seamless local experience without requiring email verification
// or external authentication.

use crate::auth::{create_user_sync, get_user, hash_password};
use crate::desktop::config::{get_default_user_id, set_default_user_id};
use crate::errors::AppError;
use crate::models::auth::RegisterPayload;
use crate::models::users::{AccountStatus, User};
use crate::schema::users;
use diesel::prelude::*;
use secrecy::SecretString;
use tracing::{debug, info};

/// Ensures a default user exists for Quick Start mode
///
/// This function checks if a default user has been created. If not, it creates
/// a "Local User" account with auto-generated secure credentials and sets the
/// account status to Active (skipping email verification for local desktop use).
///
/// The created user's ID is stored in the desktop configuration for future
/// auto-login operations.
///
/// # Arguments
/// * `conn` - Database connection to use for user creation/lookup
///
/// # Returns
/// * `Ok(User)` - The default user (either existing or newly created)
/// * `Err(AppError)` - If user creation or database operations fail
///
/// # Example
/// ```no_run
/// # use scribe_backend::desktop::ensure_default_user_exists;
/// # use scribe_backend::db::DbPool;
/// # async fn example(pool: &DbPool) -> Result<(), Box<dyn std::error::Error>> {
/// let mut conn = pool.get().await?;
/// let default_user = ensure_default_user_exists(&mut conn).await?;
/// println!("Default user ID: {}", default_user.id);
/// # Ok(())
/// # }
/// ```
pub async fn ensure_default_user_exists(conn: &mut crate::db::DbConn) -> Result<User, AppError> {
    info!("Checking for default desktop user");

    // Check if default user already exists in config
    if let Some(user_id) = get_default_user_id()? {
        // Check for NIL UUID (bug recovery)
        if user_id == crate::db::DbId::nil() {
            tracing::warn!("Found NIL user ID in desktop config. Attempting recovery...");

            // Try to find any valid (non-NIL) user in the database to recover
            // We load all users as UserDbQuery and filter in memory to avoid Diesel type inference issues with DbId::nil()
            // and because User struct is not directly Queryable (UserDbQuery is)
            let all_users_db = users::table
                .load::<crate::models::users::UserDbQuery>(conn)
                .map_err(AppError::from)?;
            let recovered_user = all_users_db
                .into_iter()
                .map(crate::models::users::User::from)
                .find(|u| u.id != crate::db::DbId::nil());

            if let Some(user) = recovered_user {
                info!(
                    user_id = %user.id,
                    "Recovered from NIL user ID by switching to existing user"
                );
                // Update config with the valid user ID
                set_default_user_id(user.id)?;
                return Ok(user);
            } else {
                info!("No other users found to recover to. Proceeding to create new user.");
                // Fall through to create new user
            }
        } else {
            debug!(
                ?user_id,
                "Default user ID found in config, attempting lookup"
            );

            // Try to fetch the user from database
            match get_user(conn, user_id) {
                Ok(user) => {
                    info!(?user_id, "Default user found and loaded");
                    return Ok(user);
                }
                Err(e) => {
                    // User ID in config but not in database (possibly deleted)
                    // Log warning and proceed to create new user
                    tracing::warn!(
                        ?user_id,
                        ?e,
                        "Default user ID in config but user not found in database, creating new user"
                    );
                }
            }
        }
    }

    info!("No default user found, creating Local User account");

    // Generate secure credentials for the default user
    // Use a random password since the user won't need to know it (auto-login)
    let random_password = generate_secure_password();

    // Create registration payload for default user
    let credentials = RegisterPayload {
        username: "LocalUser".to_string(),
        email: "local@desktop.app".to_string(), // Placeholder email for desktop mode
        password: SecretString::new(random_password.into()),
        recovery_phrase: None, // Auto-generated by create_user_sync
    };

    // Hash the password asynchronously
    let password_hash = hash_password(credentials.password.clone())
        .await
        .map_err(|e| {
            tracing::error!(?e, "Failed to hash password for default user");
            e
        })?;

    // Create the user with AccountStatus::Active (skip email verification)
    let mut user = create_user_sync(conn, credentials, password_hash).map_err(|e| {
        tracing::error!(?e, "Failed to create default user");
        AppError::from(e)
    })?;

    // Set account status to Active for desktop mode (skip email verification)
    diesel::update(users::table.find(user.id))
        .set(users::account_status.eq("active"))
        .execute(conn)
        .map_err(|e| {
            tracing::error!(?e, "Failed to activate default user account");
            AppError::from(e)
        })?;

    // Refetch user to get updated account_status
    user = get_user(conn, user.id)?;

    // Store the user ID in desktop config for future auto-login
    set_default_user_id(user.id)?;

    info!(
        user_id = %user.id,
        username = %user.username,
        "Default user created and activated successfully"
    );

    Ok(user)
}

/// Generates a cryptographically secure random password
///
/// Uses the crypto module's salt generation (which uses secure randomness)
/// to create a 32-character password suitable for desktop auto-login.
///
/// # Returns
/// A base64url-encoded random string of cryptographic quality
fn generate_secure_password() -> String {
    // Use the crypto module's salt generation which provides secure randomness
    // The salt is base64url encoded and suitable as a password
    crate::crypto::generate_salt().expect("Failed to generate secure password")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_secure_password() {
        let password1 = generate_secure_password();
        let password2 = generate_secure_password();

        // Passwords should be non-empty
        assert!(!password1.is_empty());
        assert!(!password2.is_empty());

        // Passwords should be different (with overwhelming probability)
        assert_ne!(password1, password2);

        // Passwords should be reasonable length (salt is ~32 chars base64url)
        assert!(password1.len() >= 32);
    }

    #[tokio::test]
    #[ignore] // Requires database connection
    async fn test_ensure_default_user_exists() {
        // This test would require a test database setup
        // See tests/ directory for full integration tests
    }
}
