# KMS module configuration for staging
include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "../../../../terraform/modules/kms"
}

locals {
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
}

# CRITICAL: This module creates the KMS key used for state encryption.
# Therefore, it cannot use the encryption block that depends on this key.
# We override the "encryption" block generated by the root terragrunt.hcl
# by generating an empty encryption block or one that uses S3-managed keys only if possible.
# However, OpenTofu might complain if the backend config expects encryption but the state is not.

# Strategy:
# 1. The root 'remote_state' block has 'encrypt = true' (S3 SSE). This is fine.
# 2. The root 'generate "encryption"' block configures OpenTofu client-side encryption using the KMS key.
# We must disable this client-side encryption for THIS module.


inputs = {
  environment = local.env_vars.locals.environment
  alias_name  = "alias/scribe-state-key"
}
