services:
  postgres:
    image: postgres:16 # Use a specific version for stability
    container_name: scribe_postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword # CHANGE THIS in a real production env!
      POSTGRES_DB: sanguine_scribe_dev
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent volume for data
      - ./postgres-custom.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    shm_size: 256m

  qdrant:
    # image: qdrant/qdrant:latest
    image: qdrant/qdrant:v1.14.0
    container_name: scribe_qdrant
    ports:
      - "6333:6333" # HTTP/HTTPS REST API port
      - "6334:6334" # gRPC port
    environment:
      QDRANT__SERVICE__ENABLE_TLS: "true"
      QDRANT__TLS__CERT: "/qdrant_certs/cert.pem"
      QDRANT__TLS__KEY: "/qdrant_certs/key.pem"
      # Optional: Add API key for development if needed
      # QDRANT__SERVICE__API_KEY: your-dev-api-key
    volumes:
      - qdrant_data:/qdrant/storage # Persistent volume for data
      - ./.certs:/qdrant_certs:ro # Mount host .certs dir for TLS
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data: 