-- SQLite Migration (Converted from PostgreSQL)
-- Original: up.sql
-- Conversion date: 2025-10-20T19:54:56.901926
--
-- IMPORTANT: Review warnings below and verify functionality
-- ================================================================

-- Add webhook_events table for idempotency and replay protection
-- This table tracks all processed webhook events to prevent duplicate processing

-- Note: SQLite doesn't support gen_random_uuid() - UUIDs must be generated by application

CREATE TABLE webhook_events (
    id TEXT PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    paddle_signature TEXT NOT NULL,
    payload_hash TEXT NOT NULL, -- SHA-256 hash of webhook payload
    processed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_status TEXT NOT NULL DEFAULT 'processed',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast lookup by event_id (primary idempotency check)
CREATE INDEX idx_webhook_events_event_id ON webhook_events(event_id);

-- Index for cleanup job (delete old events)
CREATE INDEX idx_webhook_events_created_at ON webhook_events(created_at DESC);

-- Table and column documentation
COMMENT ON TABLE webhook_events IS 'Tracks processed webhook events for idempotency and replay protection';
COMMENT ON COLUMN webhook_events.event_id IS 'Paddle event_id from webhook payload - globally unique across all event types';
COMMENT ON COLUMN webhook_events.event_type IS 'Type of webhook event (transaction.completed, subscription.created, etc.)';
COMMENT ON COLUMN webhook_events.paddle_signature IS 'Paddle-Signature header value for audit trail';
COMMENT ON COLUMN webhook_events.payload_hash IS 'SHA-256 hash of webhook payload for tamper detection';
COMMENT ON COLUMN webhook_events.processing_status IS 'Status of webhook processing (processed, failed, etc.)';
COMMENT ON COLUMN webhook_events.processed_at IS 'DATETIME when webhook was successfully processed';
COMMENT ON COLUMN webhook_events.created_at IS 'DATETIME when event record was created (for cleanup)';
