[package]
name = "scribe-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["multipart", "macros"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
png = "0.17"
base64 = "0.22"
thiserror = "1.0"
diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "r2d2", "serde_json", "numeric", "time"] }
diesel_migrations = { version = "2.1", features = ["postgres"] }
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["trace"] }
axum-login = { version = "0.17.0" }
bcrypt = "0.15"
secrecy = { version = "0.8", features = ["serde"] }
zip = "1.1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

anyhow = "1.0"
futures-util = "0.3"
bigdecimal = { version = "0.4.8", features = ["serde"] }

deadpool-diesel = { version = "0.5", features = ["postgres", "rt_tokio_1"] }

async-trait = "0.1"
time = { version = "0.3", features = ["serde", "serde-well-known", "macros"] }

rand = "0.8"
cookie = { version = "0.18", features = ["secure"] }
tower-cookies = "0.11"

lettre = { version = "0.11.15" }
mime = "0.3.17"
password-auth = { version = "1.0.0", features = ["argon2"] }
hex = "0.4"

tower-sessions = { version = "0.14.0", default-features = false, features = ["signed"] }

genai = "0.2.2"

[dev-dependencies]
hyper-util = { version = "0.1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "cookies"] }
serde_json = "1.0"
crc32fast = "1.4"
mime = "0.3"
http-body-util = "0.1"
cargo-tarpaulin = "0.25.2"
anyhow = "1.0.86"
once_cell = "1.19"
bytes = "1.5"
jsonwebtoken = "9"
tempfile = "3"
testcontainers = "0.21"
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
bcrypt = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
http = "1.1.0"