[package]
name = "scribe-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"

[dev-dependencies]
reqwest = "0.12"
tokio = { version = "1.37", features = ["rt", "macros"] } # Minimal features needed for testing
serde_json = "1.0.116"
