[package]
name = "scribe-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7.5", features = ["multipart"] } # <-- Added multipart feature
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
png = "0.17"
base64 = "0.22"
thiserror = "1.0"
diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "r2d2", "serde_json", "numeric"] }
diesel_migrations = { version = "2.1", features = ["postgres"] }
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
tower = { version = "0.4", features = ["util"] } # <-- Added util feature
tower-http = { version = "0.5.0", features = ["trace"] }
axum-login = { version = "0.14" }
tower-sessions = { version = "0.11" }
bcrypt = "0.15"
secrecy = { version = "0.8", features = ["serde"] }
zip = "1.1.0" # Added for CHARX parsing
# Logging dependencies
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Added for error handling and multipart
anyhow = "1.0"
futures-util = "0.3"
bigdecimal = { version = "0.4.8", features = ["serde"] }

deadpool-diesel = { version = "0.5", features = ["postgres", "rt_tokio_1"] }

# Additions for Auth
async-trait = "0.1"
time = "0.3" # Added for OffsetDateTime conversion

rand = "0.8" # Added for session key generation
# Add cookie crates for session signing
cookie = { version = "0.18", features = ["secure"] }
tower-cookies = "0.11"

[dev-dependencies]
hyper-util = { version = "0.1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "multipart"] }
serde_json = "1.0"
crc32fast = "1.4"
mime = "0.3"
http-body-util = "0.1"
cargo-tarpaulin = "0.25.2"
anyhow = "1.0"
once_cell = "1.19" # Added based on test error E0433
bytes = "1.5" # Add bytes crate
jsonwebtoken = "9" # Added for JWT handling in tests
tempfile = "3" # Added for creating temporary files in tests
