<script lang="ts">
	import AuthForm from '$lib/components/auth-form.svelte';
	import type { FormData as AuthFormData } from '$lib/components/auth-form.svelte'; // Import FormData type
	import SubmitButton from '$lib/components/submit-button.svelte';
	import { page } from '$app/stores'; // Use $app/stores for page store
	import type { ActionData } from './$types'; // Import ActionData generated by SvelteKit
	import { onMount } from 'svelte';

	// Use $props() in runes mode to get action data
	let { form }: { form?: ActionData } = $props();

	// Use $page store for route parameters
	const currentAuthTypeParam = $derived($page.params.authType);
	const signInSignUp = $derived(currentAuthTypeParam === 'signup' ? 'Sign up' : 'Sign in');
	// Map route param to AuthForm prop value using correct $derived syntax
	const authType = $derived<'login' | 'register'>(
		currentAuthTypeParam === 'signup' ? 'register' : 'login'
	);
	// Update description based on authType using correct $derived syntax
	const description = $derived(
		authType === 'register'
			? 'Use your email, username and password to sign up'
			: 'Use your email or username and password to sign in'
	);

	// Explicitly cast form to the type expected by AuthForm
	const authFormProp = $derived(form as AuthFormData | undefined);

	// Handle FIDO2 errors by suppressing them
	onMount(() => {
		// Create a custom error handler for the page
		window.addEventListener(
			'error',
			(event) => {
				// Check if the error is the FIDO2 duplicate script ID error
				if (
					event.message &&
					event.message.includes('Duplicate script ID') &&
					event.message.includes('fido2-page-script')
				) {
					// Prevent the error from propagating
					event.preventDefault();
					event.stopPropagation();
					console.log('Suppressed FIDO2 script error');
					return true;
				}
				return false;
			},
			true
		); // Use capture phase to intercept early
	});
</script>

<div
	class="flex h-dvh w-screen items-start justify-center bg-background pt-12 md:items-center md:pt-0"
>
	<div class="flex w-full max-w-md flex-col gap-12 overflow-hidden rounded-2xl">
		<div class="flex flex-col items-center justify-center gap-2 px-4 text-center sm:px-16">
			<h3 class="text-xl font-semibold dark:text-zinc-50">{signInSignUp}</h3>
			<p class="text-sm text-gray-500 dark:text-zinc-400">
				{description}
				<!-- Use dynamic description -->
			</p>
		</div>
		<!-- Pass authType prop and the explicitly cast form data -->
		<AuthForm {authType} form={authFormProp}>
			{#snippet submitButton({ pending, success })}
				<SubmitButton {pending} {success}>{signInSignUp}</SubmitButton>
			{/snippet}

			{#if authType === 'register'}
				{@render switchAuthType({
					question: 'Already have an account? ',
					href: '/signin',
					cta: 'Sign in',
					postscript: ' instead.'
				})}
			{:else}
				{@render switchAuthType({
					question: "Don't have an account? ",
					href: '/signup',
					cta: 'Sign up',
					postscript: ' for free.'
				})}
			{/if}
		</AuthForm>
	</div>
</div>

{#snippet switchAuthType({
	question,
	href,
	cta,
	postscript
}: {
	question: string;
	href: string;
	cta: string;
	postscript: string;
})}
	<p class="mt-4 text-center text-sm text-gray-600 dark:text-zinc-400">
		{question}
		<a {href} class="font-semibold text-gray-800 hover:underline dark:text-zinc-200">
			{cta}
		</a>
		{postscript}
	</p>
{/snippet}
