<script lang="ts">
	import AuthForm from '$lib/components/auth-form.svelte';
	import type { FormData as AuthFormData } from '$lib/components/auth-form.svelte'; // Import FormData type
	import SubmitButton from '$lib/components/submit-button.svelte';
	import { page } from '$app/stores'; // Use $app/stores for page store
	import type { ActionData } from './$types'; // Import ActionData generated by SvelteKit
	import { onMount } from 'svelte';
	import { toast } from 'svelte-sonner';

	// Use $props() in runes mode to get action data
	let { form }: { form?: ActionData } = $props();

	// Use $page store for route parameters
	const currentAuthTypeParam = $derived($page.params.authType);
	const signInSignUp = $derived(currentAuthTypeParam === 'signup' ? 'Sign up' : 'Sign in');
	// Map route param to AuthForm prop value using correct $derived syntax
	const authType = $derived<'login' | 'register'>(
		currentAuthTypeParam === 'signup' ? 'register' : 'login'
	);
	// Update description based on authType using correct $derived syntax
	const description = $derived(
		authType === 'register'
			? 'Use your email, username and password to sign up'
			: 'Use your email or username and password to sign in'
	);

	// Explicitly cast form to the type expected by AuthForm
	const authFormProp = $derived(form as AuthFormData | undefined);

	// Handle FIDO2 errors by suppressing them
	onMount(() => {
		// Check if this is a redirect from successful registration
		const urlParams = new URLSearchParams(window.location.search);
		if (urlParams.get('registration') === 'success') {
			toast.success('Registration successful!', {
				description: 'Please check your email to verify your account before signing in.',
				duration: 8000
			});
		}
		// Create a custom error handler for the page
		window.addEventListener(
			'error',
			(event) => {
				// Check if the error is the FIDO2 duplicate script ID error
				if (
					event.message &&
					event.message.includes('Duplicate script ID') &&
					event.message.includes('fido2-page-script')
				) {
					// Prevent the error from propagating
					event.preventDefault();
					event.stopPropagation();
					console.log('Suppressed FIDO2 script error');
					return true;
				}
				return false;
			},
			true
		); // Use capture phase to intercept early
	});
</script>

<div
	class="flex h-dvh w-screen items-start justify-center bg-background pt-12 md:items-center md:pt-0"
>
	<div class="flex w-full max-w-md flex-col gap-12 overflow-hidden rounded-2xl">
		<div class="flex flex-col items-center justify-center gap-4 px-4 text-center sm:px-16">
			<div class="flex flex-col items-center gap-3">
				<div
					class="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-purple-500 to-pink-500"
				>
					<svg class="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"
						></path>
					</svg>
				</div>
				<h1
					class="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-2xl font-bold text-transparent dark:text-zinc-50"
				>
					Sanguine Scribe
				</h1>
			</div>
			<div class="flex flex-col gap-2">
				<h3 class="text-xl font-semibold dark:text-zinc-50">{signInSignUp}</h3>
				<p class="text-sm text-gray-500 dark:text-zinc-400">
					{authType === 'register'
						? 'Create your account to start writing with AI'
						: 'Welcome back! Sign in to continue your creative journey'}
				</p>
			</div>
		</div>
		<!-- Pass authType prop and the explicitly cast form data -->
		<AuthForm {authType} form={authFormProp}>
			{#snippet submitButton({ pending, success })}
				<SubmitButton {pending} {success}>{signInSignUp}</SubmitButton>
			{/snippet}

			{#if authType === 'register'}
				{@render switchAuthType({
					question: 'Already have an account? ',
					href: '/signin',
					cta: 'Sign in',
					postscript: ' instead.'
				})}
			{:else}
				{@render switchAuthType({
					question: "Don't have an account? ",
					href: '/signup',
					cta: 'Sign up',
					postscript: ' for free.'
				})}
			{/if}
		</AuthForm>
	</div>
</div>

{#snippet switchAuthType({
	question,
	href,
	cta,
	postscript
}: {
	question: string;
	href: string;
	cta: string;
	postscript: string;
})}
	<p class="mt-4 text-center text-sm text-gray-600 dark:text-zinc-400">
		{question}
		<a {href} class="font-semibold text-gray-800 hover:underline dark:text-zinc-200">
			{cta}
		</a>
		{postscript}
	</p>
{/snippet}
