# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "scribe-opentofu-state-058264339990"
    dynamodb_table = "scribe-opentofu-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-southeast-4"
  }
}
