# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  encryption {
    key_provider "aws_kms" "main" {
      kms_key_id = "alias/scribe-state-key"
      region     = "ap-southeast-4"
      key_spec   = "AES_256"
    }

    method "aes_gcm" "main" {
      keys = key_provider.aws_kms.main
    }

    state {
      method   = method.aes_gcm.main
      enforced = true
    }

    plan {
      method   = method.aes_gcm.main
      enforced = true
    }
  }
}
