# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-southeast-4"
}

# Provider for global resources (ACM certificates for CloudFront, etc.)
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
}

# Provider for SES (Sydney)
provider "aws" {
  alias  = "ses"
  region = "ap-southeast-2"
}
