-- SQLite Migration (Converted from PostgreSQL)
-- Original: up.sql
-- Conversion date: 2025-10-19T11:15:25.496994
--
-- IMPORTANT: Review warnings below and verify functionality
-- ================================================================

-- Create message_variants table to store alternative responses for assistant messages
-- Note: SQLite doesn't support gen_random_uuid() - UUIDs must be generated by application

CREATE TABLE message_variants (
    id TEXT PRIMARY KEY,
    parent_message_id TEXT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    variant_index INTEGER NOT NULL, -- 0 = original, 1 = first variant, etc.
    content BLOB NOT NULL, -- Encrypted content
    content_nonce BLOB, -- Nonce for encryption
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Ensure unique variant indexes per parent message
    UNIQUE(parent_message_id, variant_index)
);

-- Index for performance when fetching variants for a message
CREATE INDEX idx_message_variants_parent_message_id ON message_variants(parent_message_id);

-- Index for ordering variants
CREATE INDEX idx_message_variants_parent_variant ON message_variants(parent_message_id, variant_index);

-- SQLite trigger for updating timestamps on message_variants
CREATE TRIGGER IF NOT EXISTS update_message_variants_timestamp
AFTER UPDATE ON message_variants
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at OR NEW.updated_at IS NULL
BEGIN
    UPDATE message_variants SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
