-- This file should undo anything in `up.sql`

-- Drop columns added in the corresponding up.sql file

ALTER TABLE characters
    DROP COLUMN IF EXISTS persona,
    DROP COLUMN IF EXISTS world_scenario,
    DROP COLUMN IF EXISTS avatar,
    DROP COLUMN IF EXISTS chat,
    DROP COLUMN IF EXISTS greeting,
    DROP COLUMN IF EXISTS definition,
    DROP COLUMN IF EXISTS default_voice,
    DROP COLUMN IF EXISTS extensions,
    DROP COLUMN IF EXISTS data_id,
    DROP COLUMN IF EXISTS category,
    DROP COLUMN IF EXISTS definition_visibility,
    DROP COLUMN IF EXISTS depth,
    DROP COLUMN IF EXISTS example_dialogue,
    DROP COLUMN IF EXISTS favorite,
    DROP COLUMN IF EXISTS first_message_visibility,
    DROP COLUMN IF EXISTS height,
    DROP COLUMN IF EXISTS last_activity,
    DROP COLUMN IF EXISTS migrated_from,
    DROP COLUMN IF EXISTS model_prompt,
    DROP COLUMN IF EXISTS model_prompt_visibility,
    DROP COLUMN IF EXISTS model_temperature,
    DROP COLUMN IF EXISTS num_interactions,
    DROP COLUMN IF EXISTS permanence,
    DROP COLUMN IF EXISTS persona_visibility,
    DROP COLUMN IF EXISTS revision,
    DROP COLUMN IF EXISTS sharing_visibility,
    DROP COLUMN IF EXISTS status,
    DROP COLUMN IF EXISTS system_prompt_visibility,
    DROP COLUMN IF EXISTS system_tags,
    DROP COLUMN IF EXISTS token_budget,
    DROP COLUMN IF EXISTS usage_hints,
    DROP COLUMN IF EXISTS user_persona,
    DROP COLUMN IF EXISTS user_persona_visibility,
    DROP COLUMN IF EXISTS visibility,
    DROP COLUMN IF EXISTS weight,
    DROP COLUMN IF EXISTS world_scenario_visibility;
