-- SQLite Migration (Converted from PostgreSQL)
-- Original: up.sql
-- Conversion date: 2025-10-20T19:54:56.893818
--
-- IMPORTANT: Review warnings below and verify functionality
-- ================================================================

-- Store Paddle transaction data for verification and reconciliation
-- All sensitive customer data is encrypted with user's DEK per ENCRYPTION_ARCHITECTURE.md
-- Note: SQLite doesn't support gen_random_uuid() - UUIDs must be generated by application

CREATE TABLE payment_transactions (
    id TEXT PRIMARY KEY,
    paddle_transaction_id TEXT NOT NULL UNIQUE,
    user_id TEXT REFERENCES users(id) NOT NULL,
    status TEXT NOT NULL, -- 'created', 'ready', 'billed', 'completed', 'cancelled', 'past_due'
    collection_mode TEXT, -- 'automatic', 'manual'

    -- Non-sensitive financial amounts (needed for reconciliation)
    total_cents INTEGER NOT NULL,
    tax_cents INTEGER,
    discount_cents INTEGER,
    currency_code TEXT DEFAULT 'USD',

    -- Paddle customer ID (not sensitive - just an ID)
    paddle_customer_id TEXT,

    -- All customer PII is encrypted with user's DEK
    -- This includes email, name, billing address, etc.
    customer_data_encrypted BLOB, -- Encrypted JSON with email, name, etc.
    customer_data_nonce BLOB,

    -- Items purchased (just IDs and quantities, no PII)
    items TEXT NOT NULL,

    -- Checkout ID (non-sensitive reference)
    checkout_id TEXT,

    -- Timestamps from Paddle (non-sensitive)
    billed_at DATETIME,
    completed_at DATETIME,

    -- Full transaction data from Paddle (encrypted - may contain PII)
    paddle_data_encrypted BLOB,
    paddle_data_nonce BLOB,

    -- Local timestamps
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance (only on non-encrypted fields)
CREATE INDEX idx_payment_transactions_paddle_id ON payment_transactions(paddle_transaction_id);
CREATE INDEX idx_payment_transactions_user_id ON payment_transactions(user_id);
CREATE INDEX idx_payment_transactions_paddle_customer_id ON payment_transactions(paddle_customer_id);
CREATE INDEX idx_payment_transactions_status ON payment_transactions(status);
CREATE INDEX idx_payment_transactions_created_at ON payment_transactions(created_at);
CREATE INDEX idx_payment_transactions_checkout_id ON payment_transactions(checkout_id);
